### ISSUE TITLE
开启动画好长呀。。。每次开启都要看这么久的动画=。=

### ISSUE THREAD

**Issue by AsiamCn** [Nightonke/CoCoin#2]
好费时间

**Comment by Nightonke** [comment]
那个可以调整的，在过渡Activity里面，有圆圈扩散、图标和APP名字的淡入延时，单位是毫秒。

**Comment by AsiamCn** [comment]
我是觉得。作为一个记账APP，用户点开次数频繁，每次时间很短，，不应该花费这么长时间在启动动画上~~ 
![image](https://cloud.githubusercontent.com/assets/10176630/12295904/3f1684e0-ba3f-11e5-850e-248e4cca0b06.png)

**Comment by Nightonke** [comment]
好的，等我复习完这阵改善下，谢谢你的建议～
