### ISSUE TITLE
AccountBookSettingActivity.java里面的records没定义

### ISSUE THREAD

**Issue by gexueyuan** [Nightonke/CoCoin#5]
F:\workspace\CoCoin\app\src\main\java\com\nightonke\saver\activity\AccountBookSettingActivity.java
Error:(1039, 56) 错误: 找不到符号
符号:   变量 records
位置: 类 id
注: 某些输入文件使用或覆盖了已过时的 API。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
1 个错误
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED

**Comment by Nightonke** [comment]
已修正，谢谢反馈。
