### ISSUE TITLE
如果记错一笔钱，如何删除？

### ISSUE THREAD

**Issue by caoxiangyu** [Nightonke/CoCoin#8]
如果记错一笔钱，如何删除？

**Comment by Nightonke** [comment]
By swiping the record item right in the list view.
![List](https://3.bp.blogspot.com/-XZ8Uodr6b-c/Vr7fjGMgEHI/AAAAAAAAACg/DmKQyxaaUWU/s1600/CoCoin_List.png)
As the second picture you see above.

**Comment by caoxiangyu** [comment]
thank you
